In [1]:
from pathlib import Path
import gc
import time
import warnings

import numpy as np
import pandas as pd

from scipy import sparse


from xgboost import XGBRegressor

from sklearn.model_selection import GridSearchCV, TimeSeriesSplit
from sklearn.metrics import r2_score

import joblib
RANDOM_STATE = 42

## Load Week 6 Model Data

The final Week 6 feature matrices are loaded directly instead of
re-running preprocessing and spatial feature engineering.

Using the saved matrices ensures that XGBoost and the previous models
are evaluated on exactly the same rows and features.

In [6]:
# Path to the final model-ready data saved during Week 6
data_dir = Path(
    "../data/week6_final_model_data"
)

x_train_path = data_dir / "X_train_week6.npz"
x_test_path = data_dir / "X_test_week6.npz"
y_train_path = data_dir / "y_train_week6.npy"
y_test_path = data_dir / "y_test_week6.npy"


# Confirm that all required files exist
required_paths = [
    x_train_path,
    x_test_path,
    y_train_path,
    y_test_path
]

missing_files = [
    str(path)
    for path in required_paths
    if not path.exists()
]

if missing_files:
    raise FileNotFoundError(
        "The following Week 6 files were not found:\n"
        + "\n".join(missing_files)
    )

print("All Week 6 data files were found.")
print("Data folder:", data_dir.resolve())

All Week 6 data files were found.
Data folder: D:\IDX_Exchange\IDX-Exchange-summer-2026\data\week6_final_model_data

In [7]:
# Load sparse feature matrices
X_train = sparse.load_npz(
    x_train_path
).tocsr().astype(
    np.float32,
    copy=False
)

X_test = sparse.load_npz(
    x_test_path
).tocsr().astype(
    np.float32,
    copy=False
)


# Load target arrays
y_train = np.load(
    y_train_path
).astype(
    np.float32,
    copy=False
)

y_test = np.load(
    y_test_path
).astype(
    np.float32,
    copy=False
)


print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (129813, 1165)
X_test shape: (12024, 1165)
y_train shape: (129813,)
y_test shape: (12024,)

## Data Validation

The following checks confirm that:

- The number of feature rows matches the number of targets.
- Training and testing matrices contain the same number of columns.
- The matrices contain valid finite values.
- The Week 7 models use the expected Week 6 dataset.

In [8]:
# Check row alignment
assert X_train.shape[0] == y_train.shape[0], (
    "Training features and target are not aligned."
)

assert X_test.shape[0] == y_test.shape[0], (
    "Testing features and target are not aligned."
)


# Check feature consistency
assert X_train.shape[1] == X_test.shape[1], (
    "Training and testing matrices have different feature counts."
)


# Confirm expected Week 6 dimensions
assert X_train.shape == (129813, 1165), (
    f"Unexpected training shape: {X_train.shape}"
)

assert X_test.shape == (12024, 1165), (
    f"Unexpected testing shape: {X_test.shape}"
)


# Check target values
assert np.isfinite(y_train).all(), (
    "y_train contains NaN or infinite values."
)

assert np.isfinite(y_test).all(), (
    "y_test contains NaN or infinite values."
)


# Check sparse matrix stored values
assert np.isfinite(X_train.data).all(), (
    "X_train contains NaN or infinite values."
)

assert np.isfinite(X_test.data).all(), (
    "X_test contains NaN or infinite values."
)


print("Data validation completed successfully.")
print("Training observations:", X_train.shape[0])
print("Testing observations:", X_test.shape[0])
print("Number of features:", X_train.shape[1])

Data validation completed successfully.
Training observations: 129813
Testing observations: 12024
Number of features: 1165

## Baseline XGBoost

A baseline XGBoost model is trained before hyperparameter tuning.

This provides a reference point for determining whether tuning improves
model performance.

In [9]:
# Build the baseline XGBoost regression model
baseline_xgb = XGBRegressor(
    objective="reg:squarederror",

    # Number of sequential trees
    n_estimators=100,

    # Maximum depth of each tree
    max_depth=6,

    # Contribution of each new tree
    learning_rate=0.1,

    # Faster and more memory-efficient tree construction
    tree_method="hist",

    # Evaluation loss used internally
    eval_metric="rmse",

    # Reproducibility
    random_state=RANDOM_STATE,

    # Limit CPU usage to reduce memory pressure
    n_jobs=1
)

baseline_xgb

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric='rmse', feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=1, num_parallel_tree=None, ...)

In [10]:
# Measure training time
baseline_start_time = time.time()


# Train baseline model
baseline_xgb.fit(
    X_train,
    y_train
)


baseline_training_time = (
    time.time()
    -
    baseline_start_time
)


print(
    f"Baseline XGBoost training completed in "
    f"{baseline_training_time / 60:.2f} minutes."
)

Baseline XGBoost training completed in 0.09 minutes.

In [11]:
# Generate predictions
baseline_train_predictions = baseline_xgb.predict(
    X_train
)

baseline_test_predictions = baseline_xgb.predict(
    X_test
)


# Calculate R²
baseline_train_r2 = r2_score(
    y_train,
    baseline_train_predictions
)

baseline_test_r2 = r2_score(
    y_test,
    baseline_test_predictions
)

baseline_gap = (
    baseline_train_r2
    -
    baseline_test_r2
)


print(
    f"Baseline XGBoost training R²: "
    f"{baseline_train_r2:.4f}"
)

print(
    f"Baseline XGBoost testing R²: "
    f"{baseline_test_r2:.4f}"
)

print(
    f"Baseline train-test gap: "
    f"{baseline_gap:.4f}"
)

Baseline XGBoost training R²: 0.8897
Baseline XGBoost testing R²: 0.5192
Baseline train-test gap: 0.3705

## Time-Based Cross-Validation

The training rows were previously arranged chronologically.

TimeSeriesSplit is used so that earlier observations are used to predict
later observations within each validation fold.

This is more appropriate than random cross-validation because the final
business objective is to use historical sales to predict future sales.

In [12]:
# Three time-ordered validation folds
time_cv = TimeSeriesSplit(
    n_splits=3
)

print("Number of CV splits:", time_cv.get_n_splits())

Number of CV splits: 3

In [13]:
# Display the size of each time-based fold
cv_fold_summary = []

for fold_number, (train_position, validation_position) in enumerate(
    time_cv.split(X_train),
    start=1
):
    cv_fold_summary.append(
        {
            "Fold": fold_number,
            "Training Rows": len(train_position),
            "Validation Rows": len(validation_position),
            "First Training Position": train_position[0],
            "Last Training Position": train_position[-1],
            "First Validation Position": validation_position[0],
            "Last Validation Position": validation_position[-1]
        }
    )

cv_fold_summary_df = pd.DataFrame(
    cv_fold_summary
)

display(cv_fold_summary_df)

,Fold,Training Rows,Validation Rows,First Training Position,Last Training Position,First Validation Position,Last Validation Position
0,1,32454,32453,0,32453,32454,64906
1,2,64907,32453,0,64906,64907,97359
2,3,97360,32453,0,97359,97360,129812

## Hyperparameter Tuning

The Week 7 task requires light tuning of:

- `max_depth`
- `learning_rate`
- `n_estimators`

A small parameter grid is used because the dataset contains nearly
130,000 training observations and 1,165 features.

In [18]:
# Base XGBoost estimator used by GridSearchCV
xgb_tuning_model = XGBRegressor(
    objective="reg:squarederror",
    tree_method="hist",
    eval_metric="rmse",
    random_state=RANDOM_STATE,
    n_jobs=1
)


# Light parameter grid
xgb_param_grid = {
    "max_depth": [
        6,
        7,
        8
    ],

    "learning_rate": [
         0.1,
         0.15,
         0.2
    ],

    "n_estimators": [
        200,
        300,
        400
    ]
}


# Number of parameter combinations
number_of_combinations = (
    len(xgb_param_grid["max_depth"])
    *
    len(xgb_param_grid["learning_rate"])
    *
    len(xgb_param_grid["n_estimators"])
)

number_of_fits = (
    number_of_combinations
    *
    time_cv.get_n_splits()
)


print("Parameter combinations:", number_of_combinations)
print("CV folds:", time_cv.get_n_splits())
print("Estimated total fits:", number_of_fits)

Parameter combinations: 27
CV folds: 3
Estimated total fits: 81

In [19]:
# Build the grid search
xgb_grid_search = GridSearchCV(
    estimator=xgb_tuning_model,
    param_grid=xgb_param_grid,

    # Optimize R²
    scoring="r2",

    # Preserve chronological order
    cv=time_cv,

    # One parallel job to reduce memory use
    n_jobs=1,

    # Avoid creating too many jobs in advance
    pre_dispatch=1,

    # Show progress
    verbose=2,

    # Stop immediately if a fit fails
    error_score="raise",

    # Save training scores for overfitting comparison
    return_train_score=True,

    # Automatically refit the best model on all training data
    refit=True
)

xgb_grid_search

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
             error_score='raise',
             estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, device=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=True, eval_metric='rmse',
                                    feature_types=None, feature_we...
                                    max_cat_to_onehot=None, max_delta_step=None,
                                    max_depth=None, max_leaves=None,
                                    min_child_weight=None, missing=nan,
                                    monotone_constraints=None,
                                    multi_strategy=None, n_estimators=None,
                                    n_jobs=1, num_parallel_tree=None, ...),
             n_jobs=1,
             param_grid={'learning_rate': [0.1, 0.15, 0.2],
                         'max_depth': [6, 7, 8],
                         'n_estimators': [200, 300, 400]},
             pre_dispatch=1, return_train_score=True, scoring='r2', verbose=2)

In [20]:
# Run light hyperparameter tuning
tuning_start_time = time.time()


xgb_grid_search.fit(
    X_train,
    y_train
)


tuning_training_time = (
    time.time()
    -
    tuning_start_time
)


print(
    f"Hyperparameter tuning completed in "
    f"{tuning_training_time / 60:.2f} minutes."
)

Fitting 3 folds for each of 27 candidates, totalling 81 fits
[CV] END ...learning_rate=0.1, max_depth=6, n_estimators=200; total time=   2.3s
[CV] END ...learning_rate=0.1, max_depth=6, n_estimators=200; total time=   3.0s
[CV] END ...learning_rate=0.1, max_depth=6, n_estimators=200; total time=   3.9s
[CV] END ...learning_rate=0.1, max_depth=6, n_estimators=300; total time=   3.2s
[CV] END ...learning_rate=0.1, max_depth=6, n_estimators=300; total time=   4.4s
[CV] END ...learning_rate=0.1, max_depth=6, n_estimators=300; total time=   5.9s
[CV] END ...learning_rate=0.1, max_depth=6, n_estimators=400; total time=   3.7s
[CV] END ...learning_rate=0.1, max_depth=6, n_estimators=400; total time=   5.5s
[CV] END ...learning_rate=0.1, max_depth=6, n_estimators=400; total time=   7.4s
[CV] END ...learning_rate=0.1, max_depth=7, n_estimators=200; total time=   3.1s
[CV] END ...learning_rate=0.1, max_depth=7, n_estimators=200; total time=   4.6s
[CV] END ...learning_rate=0.1, max_depth=7, n_estimators=200; total time=   5.3s
[CV] END ...learning_rate=0.1, max_depth=7, n_estimators=300; total time=   3.9s
[CV] END ...learning_rate=0.1, max_depth=7, n_estimators=300; total time=   5.6s
[CV] END ...learning_rate=0.1, max_depth=7, n_estimators=300; total time=   7.4s
[CV] END ...learning_rate=0.1, max_depth=7, n_estimators=400; total time=   5.5s
[CV] END ...learning_rate=0.1, max_depth=7, n_estimators=400; total time=   7.2s
[CV] END ...learning_rate=0.1, max_depth=7, n_estimators=400; total time=   8.9s
[CV] END ...learning_rate=0.1, max_depth=8, n_estimators=200; total time=   3.5s
[CV] END ...learning_rate=0.1, max_depth=8, n_estimators=200; total time=   5.1s
[CV] END ...learning_rate=0.1, max_depth=8, n_estimators=200; total time=   6.4s
[CV] END ...learning_rate=0.1, max_depth=8, n_estimators=300; total time=   5.1s
[CV] END ...learning_rate=0.1, max_depth=8, n_estimators=300; total time=   7.3s
[CV] END ...learning_rate=0.1, max_depth=8, n_estimators=300; total time=   9.1s
[CV] END ...learning_rate=0.1, max_depth=8, n_estimators=400; total time=   6.5s
[CV] END ...learning_rate=0.1, max_depth=8, n_estimators=400; total time=   9.4s
[CV] END ...learning_rate=0.1, max_depth=8, n_estimators=400; total time=  11.8s
[CV] END ..learning_rate=0.15, max_depth=6, n_estimators=200; total time=   2.0s
[CV] END ..learning_rate=0.15, max_depth=6, n_estimators=200; total time=   3.0s
[CV] END ..learning_rate=0.15, max_depth=6, n_estimators=200; total time=   4.1s
[CV] END ..learning_rate=0.15, max_depth=6, n_estimators=300; total time=   3.1s
[CV] END ..learning_rate=0.15, max_depth=6, n_estimators=300; total time=   4.2s
[CV] END ..learning_rate=0.15, max_depth=6, n_estimators=300; total time=   5.8s
[CV] END ..learning_rate=0.15, max_depth=6, n_estimators=400; total time=   4.0s
[CV] END ..learning_rate=0.15, max_depth=6, n_estimators=400; total time=   5.5s
[CV] END ..learning_rate=0.15, max_depth=6, n_estimators=400; total time=   7.4s
[CV] END ..learning_rate=0.15, max_depth=7, n_estimators=200; total time=   2.7s
[CV] END ..learning_rate=0.15, max_depth=7, n_estimators=200; total time=   4.2s
[CV] END ..learning_rate=0.15, max_depth=7, n_estimators=200; total time=   5.2s
[CV] END ..learning_rate=0.15, max_depth=7, n_estimators=300; total time=   3.9s
[CV] END ..learning_rate=0.15, max_depth=7, n_estimators=300; total time=   5.4s
[CV] END ..learning_rate=0.15, max_depth=7, n_estimators=300; total time=   6.9s
[CV] END ..learning_rate=0.15, max_depth=7, n_estimators=400; total time=   5.0s
[CV] END ..learning_rate=0.15, max_depth=7, n_estimators=400; total time=   6.9s
[CV] END ..learning_rate=0.15, max_depth=7, n_estimators=400; total time=   8.8s
[CV] END ..learning_rate=0.15, max_depth=8, n_estimators=200; total time=   3.8s
[CV] END ..learning_rate=0.15, max_depth=8, n_estimators=200; total time=   4.8s
[CV] END ..learning_rate=0.15, max_depth=8, n_estimators=200; total time=   6.2s
[CV] END ..learning_rate=0.15, max_depth=8, n_estimators=300; total time=   5.0s
[CV] END ..learning_rate=0.15, max_depth=8, n_estimators=300; total time=   6.9s
[CV] END ..learning_rate=0.15, max_depth=8, n_estimators=300; total time=   9.0s
[CV] END ..learning_rate=0.15, max_depth=8, n_estimators=400; total time=   6.6s
[CV] END ..learning_rate=0.15, max_depth=8, n_estimators=400; total time=   9.0s
[CV] END ..learning_rate=0.15, max_depth=8, n_estimators=400; total time=  11.1s
[CV] END ...learning_rate=0.2, max_depth=6, n_estimators=200; total time=   2.0s
[CV] END ...learning_rate=0.2, max_depth=6, n_estimators=200; total time=   2.9s
[CV] END ...learning_rate=0.2, max_depth=6, n_estimators=200; total time=   4.3s
[CV] END ...learning_rate=0.2, max_depth=6, n_estimators=300; total time=   3.2s
[CV] END ...learning_rate=0.2, max_depth=6, n_estimators=300; total time=   4.5s
[CV] END ...learning_rate=0.2, max_depth=6, n_estimators=300; total time=   6.1s
[CV] END ...learning_rate=0.2, max_depth=6, n_estimators=400; total time=   4.0s
[CV] END ...learning_rate=0.2, max_depth=6, n_estimators=400; total time=   5.4s
[CV] END ...learning_rate=0.2, max_depth=6, n_estimators=400; total time=   6.9s
[CV] END ...learning_rate=0.2, max_depth=7, n_estimators=200; total time=   2.6s
[CV] END ...learning_rate=0.2, max_depth=7, n_estimators=200; total time=   3.9s
[CV] END ...learning_rate=0.2, max_depth=7, n_estimators=200; total time=   4.6s
[CV] END ...learning_rate=0.2, max_depth=7, n_estimators=300; total time=   3.9s
[CV] END ...learning_rate=0.2, max_depth=7, n_estimators=300; total time=   6.0s
[CV] END ...learning_rate=0.2, max_depth=7, n_estimators=300; total time=   6.6s
[CV] END ...learning_rate=0.2, max_depth=7, n_estimators=400; total time=   5.1s
[CV] END ...learning_rate=0.2, max_depth=7, n_estimators=400; total time=   7.1s
[CV] END ...learning_rate=0.2, max_depth=7, n_estimators=400; total time=   8.8s
[CV] END ...learning_rate=0.2, max_depth=8, n_estimators=200; total time=   3.3s
[CV] END ...learning_rate=0.2, max_depth=8, n_estimators=200; total time=   4.8s
[CV] END ...learning_rate=0.2, max_depth=8, n_estimators=200; total time=   6.0s
[CV] END ...learning_rate=0.2, max_depth=8, n_estimators=300; total time=   4.9s
[CV] END ...learning_rate=0.2, max_depth=8, n_estimators=300; total time=   6.9s
[CV] END ...learning_rate=0.2, max_depth=8, n_estimators=300; total time=   8.5s
[CV] END ...learning_rate=0.2, max_depth=8, n_estimators=400; total time=   6.4s
[CV] END ...learning_rate=0.2, max_depth=8, n_estimators=400; total time=   9.0s
[CV] END ...learning_rate=0.2, max_depth=8, n_estimators=400; total time=  11.7s
Hyperparameter tuning completed in 9.24 minutes.

In [21]:
print("Best XGBoost parameters:")
print(xgb_grid_search.best_params_)

print(
    f"Best mean cross-validation R²: "
    f"{xgb_grid_search.best_score_:.4f}"
)

Best XGBoost parameters:
{'learning_rate': 0.15, 'max_depth': 6, 'n_estimators': 400}
Best mean cross-validation R²: 0.7185

In [22]:
# Convert all cross-validation results into a table
xgb_cv_results = pd.DataFrame(
    xgb_grid_search.cv_results_
)


xgb_cv_summary = (
    xgb_cv_results[
        [
            "param_max_depth",
            "param_learning_rate",
            "param_n_estimators",
            "mean_train_score",
            "std_train_score",
            "mean_test_score",
            "std_test_score",
            "rank_test_score",
            "mean_fit_time"
        ]
    ]
    .rename(
        columns={
            "param_max_depth": "Max Depth",
            "param_learning_rate": "Learning Rate",
            "param_n_estimators": "N Estimators",
            "mean_train_score": "Mean Train R²",
            "std_train_score": "Train R² Std",
            "mean_test_score": "Mean CV R²",
            "std_test_score": "CV R² Std",
            "rank_test_score": "CV Rank",
            "mean_fit_time": "Mean Fit Time (Seconds)"
        }
    )
    .sort_values(
        [
            "CV Rank",
            "Mean CV R²"
        ],
        ascending=[
            True,
            False
        ]
    )
    .reset_index(drop=True)
)


display(
    xgb_cv_summary.round(4)
)

,Max Depth,Learning Rate,N Estimators,Mean Train R²,Train R² Std,Mean CV R²,CV R² Std,CV Rank,Mean Fit Time (Seconds)
0,6,0.15,400,0.9649,0.0079,0.7185,0.0748,1,5.2012
1,6,0.15,300,0.9583,0.0089,0.7160,0.0742,2,4.0481
2,6,0.15,200,0.9476,0.0094,0.7109,0.0748,3,2.8402
3,7,0.15,400,0.9744,0.0064,0.7049,0.0776,4,6.3653
4,7,0.15,300,0.9696,0.0065,0.7030,0.0771,5,5.0059
5,6,0.10,400,0.9550,0.0085,0.7009,0.0641,6,5.0601
6,7,0.15,200,0.9613,0.0067,0.6993,0.0763,7,3.7749
7,6,0.10,300,0.9476,0.0092,0.6977,0.0638,8,4.1334
8,6,0.10,200,0.9361,0.0095,0.6917,0.0629,9,2.8741
9,6,0.20,400,0.9722,0.0069,0.6898,0.0613,10,4.9824
10,8,0.15,400,0.9818,0.0047,0.6878,0.0795,11,8.2602
11,6,0.20,300,0.9662,0.0081,0.6871,0.0606,12,4.2492
12,8,0.15,300,0.9779,0.0053,0.6870,0.0794,13,6.5074
13,8,0.15,200,0.9715,0.0061,0.6851,0.0792,14,4.6498
14,6,0.20,200,0.9570,0.0095,0.6843,0.0605,15,2.8898
15,7,0.10,400,0.9672,0.0071,0.6835,0.0707,16,6.6380
16,7,0.10,300,0.9617,0.0077,0.6808,0.0701,17,5.1625
17,7,0.10,200,0.9523,0.0082,0.6765,0.0696,18,4.0552
18,8,0.10,400,0.9756,0.0053,0.6742,0.0666,19,8.5919
19,7,0.20,400,0.9801,0.0056,0.6741,0.0662,20,6.4358
20,7,0.20,300,0.9756,0.0063,0.6728,0.0663,21,5.1148
21,8,0.10,300,0.9711,0.0055,0.6723,0.0666,22,6.6637
22,8,0.20,400,0.9855,0.0040,0.6721,0.0704,23,8.3984
23,8,0.20,300,0.9815,0.0047,0.6714,0.0702,24,6.2654
24,7,0.20,200,0.9685,0.0069,0.6706,0.0664,25,3.4480
25,8,0.20,200,0.9754,0.0052,0.6694,0.0701,26,4.4352
26,8,0.10,200,0.9643,0.0057,0.6690,0.0666,27,4.6672

In [23]:
# Add a train-validation gap to inspect overfitting
xgb_cv_summary["Train-CV Gap"] = (
    xgb_cv_summary["Mean Train R²"]
    -
    xgb_cv_summary["Mean CV R²"]
)

display(
    xgb_cv_summary[
        [
            "Max Depth",
            "Learning Rate",
            "N Estimators",
            "Mean Train R²",
            "Mean CV R²",
            "Train-CV Gap",
            "CV R² Std",
            "CV Rank"
        ]
    ].round(4)
)

,Max Depth,Learning Rate,N Estimators,Mean Train R²,Mean CV R²,Train-CV Gap,CV R² Std,CV Rank
0,6,0.15,400,0.9649,0.7185,0.2463,0.0748,1
1,6,0.15,300,0.9583,0.7160,0.2423,0.0742,2
2,6,0.15,200,0.9476,0.7109,0.2367,0.0748,3
3,7,0.15,400,0.9744,0.7049,0.2695,0.0776,4
4,7,0.15,300,0.9696,0.7030,0.2666,0.0771,5
5,6,0.10,400,0.9550,0.7009,0.2541,0.0641,6
6,7,0.15,200,0.9613,0.6993,0.2620,0.0763,7
7,6,0.10,300,0.9476,0.6977,0.2499,0.0638,8
8,6,0.10,200,0.9361,0.6917,0.2444,0.0629,9
9,6,0.20,400,0.9722,0.6898,0.2824,0.0613,10
10,8,0.15,400,0.9818,0.6878,0.2940,0.0795,11
11,6,0.20,300,0.9662,0.6871,0.2791,0.0606,12
12,8,0.15,300,0.9779,0.6870,0.2910,0.0794,13
13,8,0.15,200,0.9715,0.6851,0.2864,0.0792,14
14,6,0.20,200,0.9570,0.6843,0.2728,0.0605,15
15,7,0.10,400,0.9672,0.6835,0.2837,0.0707,16
16,7,0.10,300,0.9617,0.6808,0.2809,0.0701,17
17,7,0.10,200,0.9523,0.6765,0.2758,0.0696,18
18,8,0.10,400,0.9756,0.6742,0.3014,0.0666,19
19,7,0.20,400,0.9801,0.6741,0.3060,0.0662,20
20,7,0.20,300,0.9756,0.6728,0.3028,0.0663,21
21,8,0.10,300,0.9711,0.6723,0.2988,0.0666,22
22,8,0.20,400,0.9855,0.6721,0.3134,0.0704,23
23,8,0.20,300,0.9815,0.6714,0.3101,0.0702,24
24,7,0.20,200,0.9685,0.6706,0.2979,0.0664,25
25,8,0.20,200,0.9754,0.6694,0.3060,0.0701,26
26,8,0.10,200,0.9643,0.6690,0.2953,0.0666,27

## Final XGBoost Evaluation

GridSearchCV automatically refits the best parameter combination using
the complete training set.

The final test set is then used once to estimate performance on the
held-out future month.

In [25]:
# Retrieve the best refitted model
best_xgb_model = xgb_grid_search.best_estimator_

best_xgb_model

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric='rmse', feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.15, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=400,
             n_jobs=1, num_parallel_tree=None, ...)

In [26]:
# Generate final predictions
tuned_train_predictions = best_xgb_model.predict(
    X_train
)

tuned_test_predictions = best_xgb_model.predict(
    X_test
)


# Calculate final R² scores
tuned_train_r2 = r2_score(
    y_train,
    tuned_train_predictions
)

tuned_test_r2 = r2_score(
    y_test,
    tuned_test_predictions
)

tuned_train_test_gap = (
    tuned_train_r2
    -
    tuned_test_r2
)


print("Best parameters:")
print(xgb_grid_search.best_params_)

print(
    f"Best cross-validation R²: "
    f"{xgb_grid_search.best_score_:.4f}"
)

print(
    f"Tuned XGBoost training R²: "
    f"{tuned_train_r2:.4f}"
)

print(
    f"Tuned XGBoost testing R²: "
    f"{tuned_test_r2:.4f}"
)

print(
    f"Tuned train-test gap: "
    f"{tuned_train_test_gap:.4f}"
)

Best parameters:
{'learning_rate': 0.15, 'max_depth': 6, 'n_estimators': 400}
Best cross-validation R²: 0.7185
Tuned XGBoost training R²: 0.9476
Tuned XGBoost testing R²: 0.5454
Tuned train-test gap: 0.4023

Compare baseline and tuned model

In [27]:
xgb_model_comparison = pd.DataFrame(
    {
        "Model": [
            "Baseline XGBoost",
            "Tuned XGBoost"
        ],
        "Train R²": [
            baseline_train_r2,
            tuned_train_r2
        ],
        "Test R²": [
            baseline_test_r2,
            tuned_test_r2
        ],
        "Train-Test Gap": [
            baseline_gap,
            tuned_train_test_gap
        ]
    }
)


xgb_model_comparison["Test R² Change vs Baseline"] = (
    xgb_model_comparison["Test R²"]
    -
    baseline_test_r2
)


display(
    xgb_model_comparison.round(4)
)

,Model,Train R²,Test R²,Train-Test Gap,Test R² Change vs Baseline
0,Baseline XGBoost,0.8897,0.5192,0.3705,0.0000
1,Tuned XGBoost,0.9476,0.5454,0.4023,0.0262

Compare XGBoost With Previous Models

In [29]:
# Replace these values with the exact Week 6 updated-feature results
week6_linear_regression_train_r2 = 0.6616
week6_linear_regression_test_r2 = 0.4854

week6_decision_tree_train_r2 = 0.6958
week6_decision_tree_test_r2 = 0.4768

week6_random_forest_train_r2 = 0.8179
week6_random_forest_test_r2 = 0.5154

In [30]:
advanced_model_comparison = pd.DataFrame(
    {
        "Model": [
            "Linear Regression",
            "Decision Tree",
            "Random Forest",
            "Baseline XGBoost",
            "Tuned XGBoost"
        ],

        "Feature Set": [
            "Week 6 Updated Features",
            "Week 6 Updated Features",
            "Week 6 Updated Features",
            "Week 6 Updated Features",
            "Week 6 Updated Features"
        ],

        "Train R²": [
            week6_linear_regression_train_r2,
            week6_decision_tree_train_r2,
            week6_random_forest_train_r2,
            baseline_train_r2,
            tuned_train_r2
        ],

        "Test R²": [
            week6_linear_regression_test_r2,
            week6_decision_tree_test_r2,
            week6_random_forest_test_r2,
            baseline_test_r2,
            tuned_test_r2
        ]
    }
)


advanced_model_comparison["Train-Test Gap"] = (
    advanced_model_comparison["Train R²"]
    -
    advanced_model_comparison["Test R²"]
)


advanced_model_comparison = (
    advanced_model_comparison
    .sort_values(
        "Test R²",
        ascending=False
    )
    .reset_index(drop=True)
)


display(
    advanced_model_comparison.round(4)
)

,Model,Feature Set,Train R²,Test R²,Train-Test Gap
0,Tuned XGBoost,Week 6 Updated Features,0.9476,0.5454,0.4023
1,Baseline XGBoost,Week 6 Updated Features,0.8897,0.5192,0.3705
2,Random Forest,Week 6 Updated Features,0.8179,0.5154,0.3025
3,Linear Regression,Week 6 Updated Features,0.6616,0.4854,0.1762
4,Decision Tree,Week 6 Updated Features,0.6958,0.4768,0.2190